### PR TITLE
Upgrade to GraphQL 0.5.0

### PR DESCRIPTION
**Pull request by igl**
Upgrades to 0.5.0
Breaking change: https://github.com/graphql/graphql-js/pull/326

### CODE REVIEW

**Comment by matthewmueller** [comment]
thanks :-)

mind adding a test?

**Comment by igl** [comment]
can do

**Comment by igl** [comment]
Sorry for the delay. I added a little self-contained test.

**Comment by matthewmueller** [comment]
thanks!

**Comment by igl** [comment]
Thanks for the quick release. 🎈

**Pull request merged**
